// <auto-generated />
using Employees.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Employees.Migrations
{
    [DbContext(typeof(EmployeeDataContext))]
    [Migration("20240906143237_AddEmployeeSeedData")]
    partial class AddEmployeeSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Employees.Data.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Avatar")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employee", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "https://example.com/avatars/1.png",
                            City = "Musterstadt",
                            Department = "Sales",
                            Email = "max.muster@example.com",
                            FirstName = "Max",
                            LastName = "Muster",
                            PostalCode = "12345",
                            Street = "Musterstraße 1"
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "https://example.com/avatars/2.png",
                            City = "Beispielstadt",
                            Department = "Marketing",
                            Email = "erika.mustermann@example.com",
                            FirstName = "Erika",
                            LastName = "Mustermann",
                            PostalCode = "67890",
                            Street = "Beispielweg 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
